# Generated by Django 3.1.2 on 2020-10-20 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='imageLink',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
