# Generated by Django 3.1.2 on 2020-10-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20201022_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='listingsWatched',
            field=models.ManyToManyField(blank=True, related_name='watchedBy', to='auctions.Listing'),
        ),
    ]
