# Generated by Django 3.1.2 on 2020-10-23 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listing_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='status',
        ),
    ]
