# Generated by Django 3.1.2 on 2020-10-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20201023_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='imageLink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
